Microsemi/switchtec-kernel

- ntb_hw_switchtec.c
Minor issue
Crosslink BARs use 64bit addesses. Fixed the debug logging to reflect the 64bit even BAR numbers to make debugging clearer.
Original dmesg:
> [64562.048063] ntb_hw_switchtec:crosslink_enum_partition: switchtec switchtec0: Crosslink BAR0 addr: 0
> [64562.048097] ntb_hw_switchtec:crosslink_enum_partition: switchtec switchtec0: Crosslink BAR1 addr: 1000000000
> [64562.048131] ntb_hw_switchtec:crosslink_enum_partition: switchtec switchtec0: Crosslink BAR2 addr: 0
After fix:
> [63831.407219] ntb_hw_switchtec:crosslink_enum_partition: switchtec switchtec0: Crosslink BAR0 addr: 0
> [63831.407253] ntb_hw_switchtec:crosslink_enum_partition: switchtec switchtec0: Crosslink BAR2 addr: 1000000000
> [63831.407287] ntb_hw_switchtec:crosslink_enum_partition: switchtec switchtec0: Crosslink …
> Debug Print 64bit Aligned Crosslink BAR Numbers

- linux/switchtec.h
- ntb_hw_switchtec.c
For direct memory windows greater than (4G-4K), the BAR Setup Extension Registers need to be used. 
This pull request was created to resolve the 4G issue in [Issue 8: MW 2M limitation](https://github.com/Microsemi/switchtec-kernel/issues/8)
> Added NT BAR Setup Extension Registers for large MWs

- switchtec.c
to be able to allocate large memory using CMA
> Fixes #13: dma_set_coherent_mask to 64 bits

- switchtec.c
Bug Description:
For switchtec-user command event-wait, if we do not use option --partition
and --port. The command waits the event of each port. The command firstly
cleans the event of each port, then waits the event.
The bug is it just cleans the event of first port.
Root Cause:
All ports use same data 'struct switchtec_ioctl_event_ctl ctl' and the data
is changed in function event_ctl().
> BugFix - event-wait

- ntb_hw_switchtec.c
- switchtec.c
run and pass the basic test and crosslink test on both 4.16 and 4.17.
> Merge changes made in the upstream kernel for v4.16/4.17

- ntb_hw_switchtec.c
The link_sta is initialized by switchtec_ntb_link_enable() when loading
ntb_transport module. Because the peer does not load driver, the ntb link
will not be up. When the peer loads the ntb_hw_switchtec module, the
switchtec_ntb_reinit_peer() and switchtec_ntb_init_shared_mw() will be
called. The link_sta will not be re-initialized. the ntb link cannot be up.
This issue can be reproduced by following test.
Test Setup:
Host 1 <- -> Switchtec <- -> Host 2
Test Steps:
1. Load drivers on host 1
modprob   ntb
insmod switchtec.ko
insmod ntb_hw_switchtec,ko
modprob  ntb_transport 
modprob  ntb_netdev
2. Load drivers on host 2.
3. Check the NTB link 
Thanks
joey
> NTB link cannot up

- switchtec.c
change mrpc region to write combining attribute, while keep the other
region stay unchange.
previously, 1k mrpc input buffer filling took 1024 memwr tlps, with
each payload 1dwords, but only 1 byte is valid(enabled).
now, only take 16 memwr tlps with each payload 16 dwords.
> Improve mrpc efficiency by leveraging write combining

- switchtec.c
in mrpc dma mode, dma target address register with offset
0x810-0x817 and mrpc dma mode enable register with offset 0x80c in
gas space
driver set the dma target address register first, then
enable mrpc dma mode following, but because mrpc section with WC
attribute, these 2 writes were combined and resulting enable dma
first then followed by the dma target address, that's 3 dwords write
from 0x80c to 0x817, add the necessory barrier between
the memory barrier also added when disable mrpc dma
> add memory barrier between set dma target address and enable dma

- switchtec.c
p.port can is indirectly controlled by user-space, hence leading to
a potential exploitation of the Spectre variant 1 vulnerability.
This issue was detected with the help of Smatch:
drivers/pci/switch/switchtec.c:912 ioctl_port_to_pff() warn: potential spectre issue 'pcfg->dsp_pff_inst_id' [r]
Fix this by sanitizing p.port before using it to index
pcfg->dsp_pff_inst_id
Notice that given that speculation windows are large, the policy is to kill
the speculation on the first load and not worry if it can be completed with
a dependent load/store [1].
[1] https://marc.info/?l=linux-kernel&m=152449131114778&w=2
Signed-off-by: Gustavo A. R. Silva <gustavo@embeddedor.com>
Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
Acked-by: Logan Gunthorpe <logang@deltatee.com>
Cc: stable@vger.kernel.org
> switchtec: Fix Spectre v1 vulnerability

- switchtec.c
include <linux/io-64-nonatomic-lo-hi.h> so that readq/writeq is
replaced by two readl/writel on systems that do not support it
> fix compile error for readq and writeq on unsupport systems

- ntb_hw_switchtec.c
When a host is not a surviving host, but it receives the link force down massage,  it should skip the link force down massage. To reinitialize  the shared memory window, the driver just need to reinitialize the reserved LUT window.
> Enhance force down link feature.

- switchtec.c
For forward compatible, read already defined but no side effects odb
register instead of reserved register for flush WC buffer
Suggested-by: Logan Gunthorpe <logang@deltatee.com>
> switchtec: read already defined odb register for flush WC buffer

- ntb_hw_switchtec.c
When host receives the link force down message from peer host, the
ntb_hw_switchtec driver would reinitialize the shared memory window,
and NTB client(e.g. ntb_transport) would set up the translation
memory window. Because Switchtec uses same registers to set up memory
window, the access to these registers would fail and the translation
memory window would not be set up.
To fix it, we should disable link before reinitializing the shared
memory window, and enable link after it.
Signed-off-by: Joey Zhang <joey.zhang@microchip.com>
> ntb_hw_switchtec: Fix unable to set mw translation bug.

- switchtec.c
In case of two or more events happened simultaneously, MRPC event
maybe masked which lead to no more interrupt for this event,
before the next module remove and install.
In this situation, polling in 500ms time interval instead of
interrupt is leveraged, therefore the MRPC execution respond speed
is lower down evidently.
Fix this issue by skip the mask operation same as LINK event.
Reported-by: Susan He <susan.he@microchip.com>
> switchtec: Fix unintended mask of MRPC event

- ntb_hw_switchtec.c
The reinit of shared MW when receive FORCE_LINK_DOWN message is
required for non-crosslink case, because the LUT settings for shared
MW of peer is reset after reboot.
But in crosslink case, the LUT setttings in the virtual partition
will not be impact by the peer's reboot, therefore it is unnecessary
to reinit it.
> ntb_hw_switchtec: remove unnecessary shared MW reinit in crosslink case

- switchtec.c
Remove ternary operator which doesn't make sense
This commit was response of feedback from Bjorn Helgaas
in the procedure of upstream.
https://lore.kernel.org/patchwork/patch/1023094/
> switchtec: Remove unnecessary ternary operator

- switchtec.c
dma_set_coherent_mask() API query for consistent allocations.
However, that's rare case that a device driver only uses
consistent allocations. Choose the better one:
dma_set_mask_and_coherent() API, which will query the mask for
both streaming and coherent together.
> switchtec: Choose a better DMA addressing limitation query API

- ntb_hw_switchtec.c
Switchtec could support as mush as 48 partitions, but ffs & fls are
for 32 bit argument, in case of partition index larger than 31, the
current code could not parse the peer partition index correctly.
Change to the 64 bit version __ffs & __fls accordlingly to fix this
bug.
> ntb_hw_switchtec: Make partition index larger than 31 workable

- linux/switchtec.h
- switchtec.c
For the local and remote GAS access MRPC commands, the process need
to be either privileged which make it bypass all the capabilities
check in kernel or be capable of the CAP_SYS_ADMIN capability.
Check the CAP_SYS_ADMIN capability of the process which executes the
GAS access MRPC commands.
Signed-off-by: Kelvin Cao <kelvin.cao@microchip.com>
> Add permission check for the GAS access MRPC commands

- switchtec.c
Refer to Issue #74 for problem description.  Fix includes:
1) Add call to "pci_save_state()" in switchtec_pci_probe.
2) Add AER "error_detected" entry point, which disables PCI device before link reset is done.
3) Add AER "slot_reset" entry point, which reenables PCI device after link reset and clears other device state.
4) Add AER "resume" entry point, which does additional cleanup to clear AER registers state.
> Proposed fix for Issue #74 "Need support for Linux AER driver's recovery sequence for fatal AERs"

- switchtec.c
If an error is encountered when executing the MRPC command, firmware
will set status register to SWITCHTEC_MRPC_STATUS_ERROR and return
the specific error code in return value register. Fix driver to
align with this behavior.
Generally, we should treat the SWITCHTEC_MRPC_STATUS_ERROR as kind of complete of the MRPC, rather than a failure, as we still need to check the return code with this status.
> Fix an error status handling issue of MRPC

- ntb_hw_switchtec.c
In current NTB driver, we add requester IDs for RC and USP dynamically during driver initialization. This overrides the requester IDs pre-configured from config file. 
This PR adds NTB driver the capability of awareness of pre-configured requester IDs and avoid overriding them when adding new ones. And, a sysfs file ntb/requester_ids is introduced for adding, deleting and showing requester IDs dynamically at run time. 
Besides the feature changes, a minor bug in config_req_id_table()  is also fixed.
> Req id review

- linux/switchtec.h
- ntb_hw_switchtec.c
The switchtec drivers uses packed structs for MMIO addressing to the PCIe
switch BARs. Within the packed struct ntb_info_regs the u64 member ep_map
was found to be misaligned. The misalignment was discovered on an ARM64
processor through a kernel panic traced to a Load Register operation when
addressing the misaligned member. The misaligned member is currently only
being used by the ntb_hw_switchtec driver.
Dividing the misaligned u64 member into two u32 members resolves the
misalignment. Minor bitwise operations in ntb_hw_switchtec driver were
added to recover u64 value. Adding this fix will allow the ntb_hw_switchtec
driver to support the ARM64 architecture.
Signed-off-by: Paul Selles <paul.selles@microchip.com>
> Fixed misaligned MMIO data member for ARM64 support

- ntb_hw_switchtec.c
- switchtec.c
per firmware change. Firmware updated the GAS field VEP_PFF_INST_ID
in partition region to add DMA EP and NVMe EP support. Update the
drivers accordingly.
> Update the way of getting vep instance id

- switchtec.c
It was observed that after a firmware hard reset, the MRPC execution
will hang indefinitely. This is because after the reset, the host will
get all 1s for any BAR read, in which case the driver won't get a valid
MRPC status.
Add a read check to GAS access when a MRPC command execution don't
response timely, error out if the check failed.
> Error out MRPC execution when no more GAS access

- ntb_hw_switchtec.c
It was observed in a crosslink NT setup with two hosts having different
numbers of requester IDs that the traffic can go only in one direction.
In the setup, the switch of host A connects to CPU1, while the switch
of host B connects to CPU0. After loading the driver, the two hosts
have the following requester IDs. And the traffic only goes from B to A.
| Host A| Host B| 
| ---- | ----- |
|0:0.0 |0:0.0 |
|80:3.0 ||
When a TLP gose from host A to host B, it first goes from host A CPU to
the local crosslink partition (there are a pair of virtual partitions in
between the two switches in the crosslink NTB setup), with the original
requester ID be replaced with a proxy ID, then be routed to the peer
crosslink partition. If the new requester ID (prxoy ID of the local
crosslink partition) hit …
> Fix crosslink req id issue

- linux/switchtec.h
- ntb_hw_switchtec.c
ID protection is a static setting in the Switchtec config file. We
shouldn't disable it in the driver, otherwise the setting in the config
file will not take effect.
> Remove code for disabling ID protection

- ntb_hw_switchtec.c
In commit fd0edeee119ee3684d1e2e111cb6fe09a636dbb9, we corrected the requester ID registration for crosslink setup. However, this fix introduced a new competition condition we didn't take good care of. When adding a requester ID to the crosslink peer partition, it will require the NT partition state transition to take place on that partitoin. In the meantime, the peer host may be doing some other setup like creating a new LUT window which requires the state transition to take place on the same partition. 
This PR improved the code by
- Fix a minor issue in the driver removal
- Add code to check for the competition condition with retries for crosslink.
- Improve the link up/status update protocol for crosslink.
> Nt improve

- ntb_hw_switchtec.c
It was reported by a user that the on a crosslink platform where the local/crosslink partition ID are *not* 0/1, the link couldn't be brought up. 
It turns out that the doorbell message registers MMAP on the crosslink partition were not programmed. The target partitions of messages of crosslink partition are defined in the MMAP register. Without programming, it happens to map to partition 0 which is normally the host partition ID. 
To resolve this, we need to program the MMAP register of the crosslink partition. An intuitive approach is to let the host driver on the local switch to program the MMAP register of the corsslink partition. Unluckily, the driver is prohibited from accessing this register of other partitions on the same switch. 
However, the driver is able to program the MMAP …
> Fix a doorbell issue in the crosslink mode
